export {default as Collections} from './Collections/Collections'
export {default as Shoes} from './Shoes/Shoes'
export {default as Dress} from './Dress/Dress'
export {default as ShoesCollection} from './ShoesCollection/ShoesCollection'
export {default as DressCollection} from './/DressesCollection/DressesCollection'