import { images } from "../../constants";
export const shoes = [
  {
    // shoes: {
    id: "star-snikers",
    collectionId: "shoes",
    images: [
      {
        original: images.defaultImg1,
        thumbnail: images.defaultImg1,
      },
      {
        original: images.shoes1,
        thumbnail: images.shoes1,
      },
      {
        original: images.shoes2,
        thumbnail: images.shoes2,
      },
      {
        original: images.shoes3,
        thumbnail: images.shoes3,
      },
      {
        original: images.shoes4,
        thumbnail: images.shoes4,
      },
      {
        original: images.shoes5,
        thumbnail: images.shoes5,
      },
      {
        original: images.shoes6,
        thumbnail: images.shoes6,
      },
      {
        original: images.shoes7,
        thumbnail: images.shoes7,
      },
      {
        original: images.shoes8,
        thumbnail: images.shoes8,
      },
      {
        original: images.shoes9,
        thumbnail: images.shoes9,
      },
      {
        original: images.shoes10,
        thumbnail: images.shoes10,
      },
      {
        original: images.shoes11,
        thumbnail: images.shoes11,
      },
    ],
    suggestionImg: {
      view_1: images.defaultImg3,
      view_2: images.defaultImg7,
      view_3: images.defaultImg5,
      view_4: images.defaultImg2,
      view_5: images.defaultImg1,
      hoverImg_1: images.shoes3_2,
      hoverImg_2: images.shoes7_2,
      hoverImg_3: images.shoes5_2,
      hoverImg_4: images.shoes2_2,
      hoverImg_5: images.shoes2,
    },
    suggestionInfo: {
      first: "serena hight top star sneakers",
      second: "zero sneakers",
      third: "All You Need Platform Espadrille Wedges",
      fourth: "Zamela Star Sneakers",
      fifth: "paula star sneakers",
    },
    suggestionLink: {
      first: "senera-high-sneakers",
      second: "zero-sneakers",
      third: "espadrille-wedges",
      fourth: "pamela-star-sneakers",
      fifth: "star-snikers",
    },
    suggestionPrice: {
      first: 92.0,
      second: 80.0,
      third: 38.0,
      fourth: 79.0,
      fifth: 28.0,
    },
    // },
    description: {
      productName: "Aaula star sneakers",
      productPrice: 80.0,
      // productColorInfo: "color - light grey",
      productColor: [
        {
          color: "#aaa",
          sold: false,
          productColorInfo: "light grey",
        },
        { color: "orange", sold: true, productColorInfo: "black" },
        { color: "orange", sold: true, productColorInfo: "red" },
        { color: "orange", sold: false, productColorInfo: "orange" },
      ],
      productSize: [
        { size: 5.5, sold: true },
        { size: 6, sold: true },
        { size: 7, sold: false },
        { size: 7.5, sold: false },
        { size: 8, sold: false },
        { size: 8.5, sold: false },
        { size: 9, sold: false },
        { size: 10, sold: false },
        { size: 11, sold: true },
      ],
      productReady: ["In stock, ready to ship", "#54c63a"],
      productInfo:
        "The Paula Star Sneakers are here to make casual a little more glamorous! These trendy sneakers are designed with a faux suede with a white snakeskin star on the side. They have a rounded toe upper, and a classic lace-up front Style the Paula Star Sneakers with denim shorts and a graphic tee, or with a babydoll dress for a more girly look!",
      productInfo2: [
        "Faux Suede",
        "White Snakeskin Star On Side",
        "Lace-Up",
        "Rubber Sole",
        "Runs TTS",
      ],
    },
  },
  {
    id: "pamela-star-sneakers",
    images: [
      {
        original: images.defaultImg2,
        thumbnail: images.defaultImg2,
      },
      {
        original: images.shoes2_2,
        thumbnail: images.shoes2_2,
      },
      {
        original: images.shoes2_3,
        thumbnail: images.shoes2_3,
      },
      {
        original: images.shoes2_3,
        thumbnail: images.shoes2_3,
      },
      {
        original: images.shoes2_4,
        thumbnail: images.shoes2_4,
      },
      {
        original: images.shoes2_5,
        thumbnail: images.shoes2_5,
      },
      {
        original: images.shoes2_6,
        thumbnail: images.shoes2_6,
      },
      {
        original: images.shoes2_7,
        thumbnail: images.shoes2_7,
      },
    ],
    suggestionImg: {
      view_1: images.defaultImg3,
      view_2: images.defaultImg4,
      view_3: images.defaultImg5,
      view_4: images.defaultImg6,
      view_5: images.defaultImg1,
      hoverImg_1: images.shoes3_2,
      hoverImg_2: images.shoes4_2,
      hoverImg_3: images.shoes5_2,
      hoverImg_4: images.shoes6_2,
      hoverImg_5: images.shoes2,
    },
    suggestionInfo: {
      first: "serena hight top star sneakers",
      second: "Passion High Top Star Sneakers",
      third: "All You Need Platform Espadrille Wedges",
      fourth: "See Where Things Go Platform Heels",
      fifth: "paula star sneakers",
    },
    suggestionLink: {
      first: "senera-high-sneakers",
      second: "passion-high-sneakers",
      third: "espadrille-wedges",
      fourth: "platform-heels",
      fifth: "star-snikers",
    },
    suggestionPrice: {
      first: 92.0,
      second: 92.0,
      third: 38.0,
      fourth: 39.0,
      fifth: 28.0,
    },
    description: {
      productName: "Zamela star sneakers",
      productPrice: 79.0,
      // productColorInfo: "color - light grey",
      productColor: [
        {
          color: "#fff",
          sold: false,
          productColorInfo: "white",
        },
      ],
      productSize: [
        { size: 5.5, sold: true },
        { size: 6, sold: false },
        { size: 7, sold: true },
        { size: 7.5, sold: true },
        { size: 8, sold: true },
        { size: 8.5, sold: true },
        { size: 9, sold: true },
        { size: 10, sold: true },
      ],
      productReady: ["low stock - 1 item left", "orange"],
      productInfo:
        "Be the star that you are with the Pamela Star Sneakers! These trendy sneakers are designed with a white vegan leather with a black glitter detail on the back and a gold glitter star on the side. They have a rounded toe upper, a classic lace-up front, and a faux suede toe detail to finish off the look! Style the Pamela Star Sneakers with denim shorts and a graphic tee, or with a babydoll dress for a more girly look!",
      productInfo2: [
        "Vegan Leather",
        "Black Glitter Detail on Back",
        "Gold Glitter Star On Side",
        "Faux Suede Rounded Toe",
        "Lace-Up",
        "Rubber Sole",
        "Runs TTS",
      ],
    },
  },
  {
    id: "senera-high-sneakers",
    images: [
      {
        original: images.defaultImg3,
        thumbnail: images.defaultImg3,
      },
      {
        original: images.shoes3_2,
        thumbnail: images.shoes3_2,
      },
      {
        original: images.shoes3_3,
        thumbnail: images.shoes3_3,
      },
      {
        original: images.shoes3_4,
        thumbnail: images.shoes3_4,
      },
      {
        original: images.shoes3_5,
        thumbnail: images.shoes3_5,
      },
      {
        original: images.shoes3_6,
        thumbnail: images.shoes3_6,
      },
    ],
    suggestionImg: {
      view_1: images.defaultImg2,
      view_2: images.defaultImg7,
      view_3: images.defaultImg8,
      view_4: images.defaultImg6,
      view_5: images.defaultImg1,
      hoverImg_1: images.shoes2_2,
      hoverImg_2: images.shoes7_2,
      hoverImg_3: images.shoes8_2,
      hoverImg_4: images.shoes6_2,
      hoverImg_5: images.shoes2,
    },
    suggestionInfo: {
      first: "Zamela Star Sneakers",
      second: "zero sneakers",
      third: "The Best Last Sneakers",
      fourth: "See Where Things Go Platform Heels",
      fifth: "paula star sneakers",
    },
    suggestionLink: {
      first: "pamela-star-sneakers",
      second: "zero-sneakers",
      third: "last-sneakers",
      fourth: "platform-heels",
      fifth: "star-snikers",
    },
    suggestionPrice: {
      first: 80.0,
      second: 80.0,
      third: 40.0,
      fourth: 39.0,
      fifth: 28.0,
    },
    description: {
      productName: "Serena High Top Star Sneakers",
      productPrice: 92.0,
      // productColorInfo: "color - light grey",
      productColor: [
        {
          color: "#aaa",
          sold: false,
          productColorInfo: "Ligh grey",
        },
      ],
      productSize: [
        { size: 5.5, sold: true },
        { size: 6, sold: false },
        { size: 7, sold: true },
        { size: 7.5, sold: true },
        { size: 8, sold: true },
        { size: 8.5, sold: true },
        { size: 9, sold: true },
        { size: 10, sold: true },
        { size: 11, sold: true },
      ],
      productReady: ["low stock - 1 item left", "orange"],
      productInfo:
        "Like your fave song, you'll be wearing the Serena High Top Star Sneakers over and over again! These edgy sneakers are designed with a faux suede. They have a rounded toe upper, a classic lace-up front, and a white snake print star on the side to finish off the look. They also come with an extra pair of laces! Style the Serena High Top Star Sneakers with denim and a graphic tee for a trendy look!",
      productInfo2: [
        "Faux Suede",
        "White Snake Print Detail on Side",
        "High Top Design",
        "Rounded Toe",
        " Lace-Up",
        "Rubber Sole",
        "Extra Pair of Laces Included",
        "Runs TTS",
      ],
    },
    // },
  },
  {
    id: "passion-high-sneakers",
    images: [
      {
        original: images.defaultImg4,
        thumbnail: images.defaultImg4,
      },
      {
        original: images.shoes4_2,
        thumbnail: images.shoes4_2,
      },
      {
        original: images.shoes4_3,
        thumbnail: images.shoes4_3,
      },
      {
        original: images.shoes4_4,
        thumbnail: images.shoes4_4,
      },
      {
        original: images.shoes4_5,
        thumbnail: images.shoes4_5,
      },
      {
        original: images.shoes4_6,
        thumbnail: images.shoes4_6,
      },
      {
        original: images.shoes4_7,
        thumbnail: images.shoes4_7,
      },
      {
        original: images.shoes4_8,
        thumbnail: images.shoes4_8,
      },
      {
        original: images.shoes4_9,
        thumbnail: images.shoes4_9,
      },
      {
        original: images.shoes4_10,
        thumbnail: images.shoes4_10,
      },
      {
        original: images.shoes4_11,
        thumbnail: images.shoes4_11,
      },
    ],
    suggestionImg: {
      view_1: images.defaultImg3,
      view_2: images.defaultImg7,
      view_3: images.defaultImg5,
      view_4: images.defaultImg6,
      view_5: images.defaultImg1,
      hoverImg_1: images.shoes3_2,
      hoverImg_2: images.shoes7_2,
      hoverImg_3: images.shoes5_2,
      hoverImg_4: images.shoes6_2,
      hoverImg_5: images.shoes2,
    },
    suggestionInfo: {
      first: "serena hight top star sneakers",
      second: "zero sneakers",
      third: "All You Need Platform Espadrille Wedges",
      fourth: "See Where Things Go Platform Heels",
      fifth: "paula star sneakers",
    },
    suggestionLink: {
      first: "senera-high-sneakers",
      second: "zero-sneakers",
      third: "espadrille-wedges",
      fourth: "platform-heels",
      fifth: "star-snikers",
    },
    suggestionPrice: {
      first: 28.0,
      second: 80.0,
      third: 38.0,
      fourth: 39.0,
      fifth: 28.0,
    },
    description: {
      productName: "Serena High Top Star Sneakers",
      productPrice: 92.0,
      // productColorInfo: "color - light grey",
      productColor: [
        {
          color: "#aaa",
          sold: false,
          productColorInfo: "Ligh grey",
        },
      ],
      productSize: [
        { size: 5.5, sold: true },
        { size: 6, sold: false },
        { size: 7, sold: true },
        { size: 7.5, sold: true },
        { size: 8, sold: true },
        { size: 8.5, sold: true },
        { size: 9, sold: true },
        { size: 10, sold: true },
        { size: 11, sold: true },
      ],
      productReady: ["low stock - 1 item left", "orange"],
      productInfo:
        "Like your fave song, you'll be wearing the Serena High Top Star Sneakers over and over again! These edgy sneakers are designed with a faux suede. They have a rounded toe upper, a classic lace-up front, and a white snake print star on the side to finish off the look. They also come with an extra pair of laces! Style the Serena High Top Star Sneakers with denim and a graphic tee for a trendy look!",
      productInfo2: [
        "Faux Suede",
        "White Snake Print Detail on Side",
        "High Top Design",
        "Rounded Toe",
        " Lace-Up",
        "Rubber Sole",
        "Extra Pair of Laces Included",
        "Runs TTS",
      ],
    },
    // },
  },
  // ----------------------------------------- 555 //
  {
    id: "espadrille-wedges",
    images: [
      {
        original: images.defaultImg5,
        thumbnail: images.defaultImg5,
      },
      {
        original: images.shoes5_2,
        thumbnail: images.shoes5_2,
      },
      {
        original: images.shoes5_3,
        thumbnail: images.shoes5_3,
      },
    ],
    suggestionImg: {
      view_1: images.defaultImg3,
      view_2: images.defaultImg7,
      view_3: images.defaultImg5,
      view_4: images.defaultImg6,
      view_5: images.defaultImg1,
      hoverImg_1: images.shoes3_2,
      hoverImg_2: images.shoes7_2,
      hoverImg_3: images.shoes5_2,
      hoverImg_4: images.shoes6_2,
      hoverImg_5: images.shoes2,
    },
    suggestionInfo: {
      first: "serena hight top star sneakers",
      second: "zero sneakers",
      third: "All You Need Platform Espadrille Wedges",
      fourth: "See Where Things Go Platform Heels",
      fifth: "paula star sneakers",
    },
    suggestionLink: {
      first: "senera-high-sneakers",
      second: "zero-sneakers",
      third: "espadrille-wedges",
      fourth: "platform-heels",
      fifth: "star-snikers",
    },
    suggestionPrice: {
      first: 28.0,
      second: 80.0,
      third: 38.0,
      fourth: 39.0,
      fifth: 28.0,
    },
    description: {
      productName: "All You Need Platform Espadrille Wedges",
      productPrice: 38.0,
      // productColorInfo: "color - light grey",
      productColor: [
        {
          color: "#ecdac9",
          sold: false,
          productColorInfo: "natural",
        },
      ],
      productSize: [
        { size: 5.5, sold: false },
        { size: 6, sold: false },
        { size: 7, sold: false },
        { size: 7.5, sold: false },
        { size: 8, sold: true },
        { size: 8.5, sold: false },
        { size: 9, sold: false },
        { size: 10, sold: false },
        { size: 11, sold: true },
      ],
      productReady: ["low stock - 1 item left", "orange"],
      productInfo:
        "The All You Need Platform Espadrille Wedges will quickly become your go-to shoes for summer! These cute sandals are designed with criss-cross straps across the foot and a braided jute espadrille platform wedge. Style the All You Need Platform Espadrille Wedges with a maxi dress and gold jewelry!",
      productInfo2: [
        "Criss-Cross Straps",
        "Espadrille Platform + Wedge",
        "Runs TTS",
      ],
    },
  },
  // ----------------------------------------- 666 //
  {
    id: "platform-heels",
    images: [
      {
        original: images.defaultImg6,
        thumbnail: images.defaultImg6,
      },
      {
        original: images.shoes6_2,
        thumbnail: images.shoes6_2,
      },
      {
        original: images.shoes6_3,
        thumbnail: images.shoes6_3,
      },
      {
        original: images.shoes6_4,
        thumbnail: images.shoes6_4,
      },
      {
        original: images.shoes6_5,
        thumbnail: images.shoes6_5,
      },
    ],
    suggestionImg: {
      view_1: images.defaultImg3,
      view_2: images.defaultImg7,
      view_3: images.defaultImg5,
      view_4: images.defaultImg6,
      view_5: images.defaultImg1,
      hoverImg_1: images.shoes3_2,
      hoverImg_2: images.shoes7_2,
      hoverImg_3: images.shoes5_2,
      hoverImg_4: images.shoes6_2,
      hoverImg_5: images.shoes2,
    },
    suggestionInfo: {
      first: "serena hight top star sneakers",
      second: "zero sneakers",
      third: "All You Need Platform Espadrille Wedges",
      fourth: "See Where Things Go Platform Heels",
      fifth: "paula star sneakers",
    },
    suggestionLink: {
      first: "senera-high-sneakers",
      second: "zero-sneakers",
      third: "espadrille-wedges",
      fourth: "platform-heels",
      fifth: "star-snikers",
    },
    suggestionPrice: {
      first: 28.0,
      second: 80.0,
      third: 38.0,
      fourth: 39.0,
      fifth: 28.0,
    },
    description: {
      productName: "See Where Things Go Platform Heels",
      productPrice: 39.0,
      productColor: [
        {
          color: "#d5bfaf",
          sold: false,
          productColorInfo: "taupe",
        },
      ],
      productSize: [
        { size: 5.5, sold: true },
        { size: 6, sold: true },
        { size: 7, sold: true },
        { size: 7.5, sold: true },
        { size: 8, sold: true },
        { size: 8.5, sold: false },
        { size: 9, sold: false },
        { size: 10, sold: false },
        { size: 11, sold: true },
      ],
      productReady: ["low stock - 1 item left", "orange"],
      productInfo:
        "See where the day takes you when you're wearing the See Where Things Go Platform Heels! These trendy shoes are designed with a soft faux leather. They feature a toe strap with an adjustable ankle strap with a buckle and a walkable wooden platform heel. Style the See Where Things Go Platform Heels with maxi skirts or mini dresses for an elevated look!",
      productInfo2: [
        "Faux Leather",
        "Toe Strap",
        "Adjustable Ankle Strap",
        "Wooden Platform Heel",
        "Runs TTS",
      ],
    },
  },
  // ----------------------------------------- 777 //
  {
    id: "zero-sneakers",
    images: [
      {
        original: images.defaultImg7,
        thumbnail: images.defaultImg7,
      },
      {
        original: images.shoes7_2,
        thumbnail: images.shoes7_2,
      },
      {
        original: images.shoes7_3,
        thumbnail: images.shoes7_3,
      },
      {
        original: images.shoes7_4,
        thumbnail: images.shoes7_4,
      },
      {
        original: images.shoes7_5,
        thumbnail: images.shoes7_5,
      },
      {
        original: images.shoes7_6,
        thumbnail: images.shoes7_6,
      },
    ],
    suggestionImg: {
      view_1: images.defaultImg3,
      view_2: images.defaultImg7,
      view_3: images.defaultImg5,
      view_4: images.defaultImg6,
      view_5: images.defaultImg1,
      hoverImg_1: images.shoes3_2,
      hoverImg_2: images.shoes7_2,
      hoverImg_3: images.shoes5_2,
      hoverImg_4: images.shoes6_2,
      hoverImg_5: images.shoes2,
    },
    suggestionInfo: {
      first: "serena hight top star sneakers",
      second: "zero sneakers",
      third: "All You Need Platform Espadrille Wedges",
      fourth: "See Where Things Go Platform Heels",
      fifth: "paula star sneakers",
    },
    suggestionLink: {
      first: "senera-high-sneakers",
      second: "zero-sneakers",
      third: "espadrille-wedges",
      fourth: "platform-heels",
      fifth: "star-snikers",
    },
    suggestionPrice: {
      first: 28.0,
      second: 80.0,
      third: 38.0,
      fourth: 39.0,
      fifth: 28.0,
    },
    description: {
      productName: "zero sneakers",
      productPrice: 80.0,
      productColor: [
        {
          color: "#d5bfaf",
          sold: false,
          productColorInfo: "taupe",
        },
      ],
      productSize: [
        { size: 5.5, sold: true },
        { size: 6, sold: false },
        { size: 7, sold: true },
        { size: 7.5, sold: false },
        { size: 8, sold: true },
        { size: 8.5, sold: false },
        { size: 9, sold: false },
        { size: 10, sold: false },
        { size: 11, sold: true },
      ],
      productReady: ["low stock - 3 item left", "orange"],
      productInfo:
        "See where the day takes you when you're wearing the See Where Things Go Platform Heels! These trendy shoes are designed with a soft faux leather. They feature a toe strap with an adjustable ankle strap with a buckle and a walkable wooden platform heel. Style the See Where Things Go Platform Heels with maxi skirts or mini dresses for an elevated look!",
      productInfo2: [
        "Faux Leather",
        "Toe Strap",
        "Wooden Platform Heel",
        "Runs TTS",
      ],
    },
  },
  // ----------------------------------------- 888 //
  {
    id: "last-sneakers",
    images: [
      {
        original: images.defaultImg8,
        thumbnail: images.defaultImg8,
      },
      {
        original: images.shoes8_2,
        thumbnail: images.shoes8_2,
      },
      {
        original: images.shoes8_3,
        thumbnail: images.shoes8_3,
      },
      {
        original: images.shoes8_4,
        thumbnail: images.shoes8_4,
      },
      {
        original: images.shoes8_5,
        thumbnail: images.shoes8_5,
      },
      {
        original: images.shoes8_6,
        thumbnail: images.shoes8_6,
      },
      {
        original: images.shoes8_7,
        thumbnail: images.shoes8_7,
      },
      {
        original: images.shoes8_8,
        thumbnail: images.shoes8_8,
      },
      {
        original: images.shoes8_9,
        thumbnail: images.shoes8_9,
      },
      {
        original: images.shoes8_10,
        thumbnail: images.shoes8_10,
      },
      {
        original: images.shoes8_11,
        thumbnail: images.shoes8_11,
      },
    ],
    suggestionImg: {
      view_1: images.defaultImg3,
      view_2: images.defaultImg7,
      view_3: images.defaultImg5,
      view_4: images.defaultImg6,
      view_5: images.defaultImg1,
      hoverImg_1: images.shoes3_2,
      hoverImg_2: images.shoes7_2,
      hoverImg_3: images.shoes5_2,
      hoverImg_4: images.shoes6_2,
      hoverImg_5: images.shoes2,
    },
    suggestionInfo: {
      first: "serena hight top star sneakers",
      second: "zero sneakers",
      third: "All You Need Platform Espadrille Wedges",
      fourth: "See Where Things Go Platform Heels",
      fifth: "paula star sneakers",
    },
    suggestionLink: {
      first: "senera-high-sneakers",
      second: "zero-sneakers",
      third: "espadrille-wedges",
      fourth: "platform-heels",
      fifth: "star-snikers",
    },
    suggestionPrice: {
      first: 28.0,
      second: 80.0,
      third: 38.0,
      fourth: 39.0,
      fifth: 28.0,
    },
    description: {
      productName: "the best last sneakers",
      productPrice: 40.0,
      productColor: [
        {
          color: "#fff",
          sold: false,
          productColorInfo: "white",
        },
        {
          color: "orange",
          sold: false,
          productColorInfo: "orange",
        },
        {
          color: "#212121",
          sold: false,
          productColorInfo: "black",
        },
      ],
      productSize: [
        { size: 5.5, sold: true },
        { size: 6, sold: false },
        { size: 7, sold: true },
        { size: 7.5, sold: false },
        { size: 8, sold: true },
        { size: 8.5, sold: false },
        { size: 9, sold: true },
        { size: 10, sold: false },
        { size: 11, sold: true },
      ],
      productReady: ["low stock - 4 item left", "orange"],
      productInfo:
        "See where the day takes you when you're wearing the See Where Things Go Platform Heels!  They feature a toe strap with an adjustable ankle strap with a buckle and a walkable wooden platform heel. Style the See Where Things Go Platform Heels with maxi skirts or mini dresses for an elevated look!",
      productInfo2: ["Faux Leather", "Toe Strap", "Runs TTS"],
    },
  },
];

export const dresses = [
  {
    id: "better-together-t-shirt",
    collectionId: "dress",
    images: [
      {
        original: images.dress1_1,
        thumbnail: images.dress1_1,
      },
      {
        original: images.dress1_2,
        thumbnail: images.dress1_2,
      },
      {
        original: images.dress1_3,
        thumbnail: images.dress1_3,
      },
      {
        original: images.dress1_4,
        thumbnail: images.dress1_4,
      },
      {
        original: images.dress1_5,
        thumbnail: images.dress1_5,
      },
      {
        original: images.dress1_6,
        thumbnail: images.dress1_6,
      },
      {
        original: images.dress1_7,
        thumbnail: images.dress1_7,
      },
      {
        original: images.dress1_8,
        thumbnail: images.dress1_8,
      },
    ],
    suggestionImg: {
      view_1: images.dress2_1,
      view_2: images.dress5_1,
      view_3: images.dress4_1,
      view_4: images.dress7_1,
      view_5: images.dress6_1,
      hoverImg_1: images.dress2_2,
      hoverImg_2: images.dress5_2,
      hoverImg_3: images.dress4_2,
      hoverImg_4: images.dress7_2,
      hoverImg_5: images.dress6_2,
    },
    suggestionInfo: {
      first: "Easy On The Eyes Midi Dress",
      second: "Got You Hooked Midi Dress",
      third: "Steal My Heart Linen Tunic",
      fourth: "Ocean Waves Halter Maxi Dress",
      fifth: "paula star sneakers",
    },
    suggestionLink: {
      first: "midi-dress",
      second: "got-you-hooked",
      third: "steal-my-heart",
      fourth: "ocean-waves",
      fifth: "my-heart-goes-midi",
    },
    suggestionPrice: {
      first: 15.0,
      second: 10.0,
      third: 10.0,
      fourth: 20.0,
      fifth: 15.0,
    },
    description: {
      productName: "Better Together T-Shirt Dress",
      productPrice: 15.0,
      productColor: [
        {
          color: "#d5bfaf",
          sold: false,
          productColorInfo: "taupa",
        },
        { color: "#d4def1", sold: true, productColorInfo: "Light Blue" },
        { color: "#212121", sold: false, productColorInfo: "black" },
      ],
      productSize: [
        { size: "small", sold: false },
        { size: "medium", sold: false },
        { size: "large", sold: false },
      ],
      productReady: ["Low stock - 9 items left", "orange"],
      productInfo:
        "The Better Together T-Shirt Dress is a number that is sure to beckon you from your closet! This cute dress is designed with a soft and stretchy knit. It features a rounded neckline, short rolled sleeves, and a relaxed fit with a front pocket and side pockets that ends at a mini length. Style the Better Together T-Shirt Dress with sneakers for a casual yet cute outfit! Available in 3 colors.",
      productInfo2: [
        "Soft + Stretchy Knit Fabrication",
        "Rounded Neckline",
        " Short Rolled Sleeves",
        "Relaxed Fit",
        "Front Pocket",
        "Side Pockets",
        "Short/Mini Length",
        "Made in the USA",
        "100% Cotton",
        "Hand Wash Cold, Hang or Line Dry",
        "Model is 5'4' and wearing a Small.",
      ],
    },
  },
  // --------------------------------2 2 2
  {
    id: "midi-dress",
    collectionId: "dress",
    images: [
      {
        original: images.dress2_1,
        thumbnail: images.dress2_1,
      },
      {
        original: images.dress2_2,
        thumbnail: images.dress2_2,
      },
      {
        original: images.dress2_3,
        thumbnail: images.dress2_3,
      },
      {
        original: images.dress2_4,
        thumbnail: images.dress2_4,
      },
      {
        original: images.dress2_5,
        thumbnail: images.dress2_5,
      },
      {
        original: images.dress2_6,
        thumbnail: images.dress2_6,
      },
      {
        original: images.dress2_7,
        thumbnail: images.dress2_7,
      },
    ],
    suggestionImg: {
      view_1: images.dress1_1,
      view_2: images.dress5_1,
      view_3: images.dress4_1,
      view_4: images.dress7_1,
      view_5: images.dress6_1,
      hoverImg_1: images.dress1_2,
      hoverImg_2: images.dress5_2,
      hoverImg_3: images.dress4_2,
      hoverImg_4: images.dress7_2,
      hoverImg_5: images.dress6_2,
    },
    suggestionInfo: {
      first: "Better Together T-Shirt Dress",
      second: "Got You Hooked Midi Dress",
      third: "Steal My Heart Linen Tunic",
      fourth: "Ocean Waves Halter Maxi Dress",
      fifth: "paula star sneakers",
    },
    suggestionLink: {
      first: "better-together-t-shirt",
      second: "got-you-hooked",
      third: "steal-my-heart",
      fourth: "ocean-waves",
      fifth: "my-heart-goes-midi",
    },
    suggestionPrice: {
      first: 15.0,
      second: 10.0,
      third: 10.0,
      fourth: 20.0,
      fifth: 15.0,
    },
    description: {
      productName: "Easy On The Eyes Midi Dress",
      productPrice: 15.0,
      productColor: [
        {
          color: "#f7a28b",
          sold: false,
          productColorInfo: "peach",
        },
        { color: "#d4def1", sold: true, productColorInfo: "Light Blue" },
      ],
      productSize: [
        { size: "small", sold: true },
        { size: "large", sold: true },
        { size: "medium", sold: false },
        { size: "X-large", sold: false },
      ],
      productReady: ["In stock, ready to ship", "#55c53a"],
      productInfo:
        "Let the compliments flood in when you wear the Easy On The Eyes Midi Dress! This comfy dress is made of a soft and stretchy knit. It features a rounded neckline, a sleeveless bodice with ruching on the shoulders, a functional drawstring waistband, and a relaxed fit with a high-low hem that ends at a midi length. Style the Easy On The Eyes Midi Dress with a straw hat and sandals for an easy summer look! Available in 2 colors.",
      productInfo2: [
        "Soft + Stretchy Knit Fabrication",
        "Rounded Neckline",
        " Short Rolled Sleeves",
        "Relaxed Fit",
        "Front Pocket",
        "Side Pockets",
        "Short/Mini Length",
        "Made in the USA",
        "100% Cotton",
        "Hand Wash Cold, Hang or Line Dry",
        "Model is 5'4' and wearing a Small.",
      ],
    },
  },
  // --------------------------------3 3 3
  {
    id: "frash-florals-babydoll",
    collectionId: "dress",
    images: [
      {
        original: images.dress3_1,
        thumbnail: images.dress3_1,
      },
      {
        original: images.dress3_2,
        thumbnail: images.dress3_2,
      },
      {
        original: images.dress3_3,
        thumbnail: images.dress3_3,
      },
      {
        original: images.dress3_4,
        thumbnail: images.dress3_4,
      },
      {
        original: images.dress3_5,
        thumbnail: images.dress3_5,
      },
      {
        original: images.dress3_6,
        thumbnail: images.dress3_6,
      },
      {
        original: images.dress3_7,
        thumbnail: images.dress3_7,
      },
      {
        original: images.dress3_8,
        thumbnail: images.dress3_8,
      },
      {
        original: images.dress3_9,
        thumbnail: images.dress3_9,
      },
    ],
    suggestionImg: {
      view_1: images.dress1_1,
      view_2: images.dress5_1,
      view_3: images.dress4_1,
      view_4: images.dress7_1,
      view_5: images.dress6_1,
      hoverImg_1: images.dress1_2,
      hoverImg_2: images.dress5_2,
      hoverImg_3: images.dress4_2,
      hoverImg_4: images.dress7_2,
      hoverImg_5: images.dress6_2,
    },
    suggestionInfo: {
      first: "Better Together T-Shirt Dress",
      second: "Got You Hooked Midi Dress",
      third: "Steal My Heart Linen Tunic",
      fourth: "Ocean Waves Halter Maxi Dress",
      fifth: "paula star sneakers",
    },
    suggestionLink: {
      first: "better-together-t-shirt",
      second: "got-you-hooked",
      third: "steal-my-heart",
      fourth: "ocean-waves",
      fifth: "my-heart-goes-midi",
    },
    suggestionPrice: {
      first: 15.0,
      second: 10.0,
      third: 10.0,
      fourth: 20.0,
      fifth: 15.0,
    },
    description: {
      productName: "Fresh Florals Babydoll Mini Dress",
      productPrice: 20.0,
      productColor: [
        {
          color: "#f7a28b",
          sold: true,
          productColorInfo: "peach",
        },
        { color: "#0551a4", sold: false, productColorInfo: "Blue" },
        { color: "#f7b1cb", sold: false, productColorInfo: "Pink" },
      ],
      productSize: [
        { size: "small", sold: true },
        { size: "large", sold: false },
        { size: "medium", sold: false },
      ],
      productReady: ["In stock, ready to ship", "#55c53a"],
      productInfo:
        "Looking like a botanical beauty has never been so effortless than with the Fresh Florals Babydoll Mini Dress! This adorable dress is designed with a textured lightweight woven knit in a floral print. It features a square neckline, short puff sleeves with elastic cuffs, elastic shoulders, and a flowy babydoll fit with a back zipper that ends at a mini length. It also has side pockets! Style the Fresh Florals Babydoll Mini Dress with heels and gold jewelry for a girly summer outfit!",
      productInfo2: [
        "Soft + Stretchy Knit Fabrication",
        "Rounded Neckline",
        " Short Rolled Sleeves",
        "Relaxed Fit",
        "Front Pocket",
        "Side Pockets",
        "Short/Mini Length",
        "Made in the USA",
        "100% Cotton",
        "Hand Wash Cold, Hang or Line Dry",
        "Model is 5'4' and wearing a Small.",
      ],
    },
  },
  // --------------------------------4 4 4
  {
    id: "steal-my-heart",
    collectionId: "dress",
    images: [
      {
        original: images.dress4_1,
        thumbnail: images.dress4_1,
      },
      {
        original: images.dress4_2,
        thumbnail: images.dress4_2,
      },
      {
        original: images.dress4_3,
        thumbnail: images.dress4_3,
      },
      {
        original: images.dress4_4,
        thumbnail: images.dress4_4,
      },
      {
        original: images.dress4_5,
        thumbnail: images.dress4_5,
      },
      {
        original: images.dress4_6,
        thumbnail: images.dress4_6,
      },
      {
        original: images.dress4_7,
        thumbnail: images.dress4_7,
      },
    ],
    suggestionImg: {
      view_1: images.dress1_1,
      view_2: images.dress5_1,
      view_3: images.dress3_1,
      view_4: images.dress7_1,
      view_5: images.dress6_1,
      hoverImg_1: images.dress1_2,
      hoverImg_2: images.dress5_2,
      hoverImg_3: images.dress3_2,
      hoverImg_4: images.dress7_2,
      hoverImg_5: images.dress6_2,
    },
    suggestionInfo: {
      first: "Better Together T-Shirt Dress",
      second: "Got You Hooked Midi Dress",
      third: "Fresh Florals Babydoll Mini Dress",
      fourth: "Ocean Waves Halter Maxi Dress",
      fifth: "paula star sneakers",
    },
    suggestionLink: {
      first: "better-together-t-shirt",
      second: "got-you-hooked",
      third: "frash-florals-babydoll",
      fourth: "ocean-waves",
      fifth: "my-heart-goes-midi",
    },
    suggestionPrice: {
      first: 15.0,
      second: 10.0,
      third: 20.0,
      fourth: 20.0,
      fifth: 15.0,
    },
    description: {
      productName: "Steal My Heart Linen Tunic",
      productPrice: 10.0,
      productColor: [
        {
          color: "#a3bad2",
          sold: false,
          productColorInfo: "denim",
        },
        { color: "#7b605e", sold: false, productColorInfo: "mocha" },
      ],
      productSize: [
        { size: "small", sold: false },
        { size: "large", sold: false },
        { size: "medium", sold: false },
      ],
      productReady: ["In stock, ready to ship", "#55c53a"],
      productInfo:
        "The Steal My Heart Linen Tunic has us believing in love at first sight! This cute top is designed with a lightweight crinkle linen material. It features a notched v-neckline with a functional snap, long rolled sleeves, and an oversized fit with a high-low hem. It also has side pockets! Style the Steal My Heart Linen Tunic with your favorite denim + booties for a boho look! Available in 2 colors.",
      productInfo2: [
        "Soft + Stretchy Knit Fabrication",
        "Rounded Neckline",
        " Short Rolled Sleeves",
        "Relaxed Fit",
        "Front Pocket",
        "Side Pockets",
        "Short/Mini Length",
        "Made in the USA",
        "100% Cotton",
        "Hand Wash Cold, Hang or Line Dry",
        "Model is 5'4' and wearing a Small.",
      ],
    },
  },
  // --------------------------------5 5 5
  {
    id: "got-you-hooked",
    collectionId: "dress",
    images: [
      {
        original: images.dress5_1,
        thumbnail: images.dress5_1,
      },
      {
        original: images.dress5_2,
        thumbnail: images.dress5_2,
      },
      {
        original: images.dress5_3,
        thumbnail: images.dress5_3,
      },
      {
        original: images.dress5_4,
        thumbnail: images.dress5_4,
      },
      {
        original: images.dress5_5,
        thumbnail: images.dress5_5,
      },
      {
        original: images.dress5_6,
        thumbnail: images.dress5_6,
      },
    ],
    suggestionImg: {
      view_1: images.dress1_1,
      view_2: images.dress2_1,
      view_3: images.dress3_1,
      view_4: images.dress7_1,
      view_5: images.dress6_1,
      hoverImg_1: images.dress1_2,
      hoverImg_2: images.dress2_2,
      hoverImg_3: images.dress3_2,
      hoverImg_4: images.dress7_2,
      hoverImg_5: images.dress6_2,
    },
    suggestionInfo: {
      first: "Better Together T-Shirt Dress",
      second: "Easy On The Eyes Midi Dress",
      third: "Fresh Florals Babydoll Mini Dress",
      fourth: "Ocean Waves Halter Maxi Dress",
      fifth: "paula star sneakers",
    },
    suggestionLink: {
      first: "better-together-t-shirt",
      second: "midi-dress",
      third: "frash-florals-babydoll",
      fourth: "ocean-waves",
      fifth: "my-heart-goes-midi",
    },
    suggestionPrice: {
      first: 15.0,
      second: 15.0,
      third: 20.0,
      fourth: 20.0,
      fifth: 15.0,
    },
    description: {
      productName: "Got You Hooked Midi Dress",
      productPrice: 10.0,
      productColor: [
        {
          color: "#212121",
          sold: false,
          productColorInfo: "black",
        },
        { color: "#67696b", sold: false, productColorInfo: "charcoal" },
        { color: "#4e4e41", sold: false, productColorInfo: "olive" },
        { color: "#60463f", sold: false, productColorInfo: "brown" },
        { color: "#60463f", sold: true, productColorInfo: "brown" },
      ],
      productSize: [
        { size: "small", sold: false },
        { size: "large", sold: false },
        { size: "medium", sold: true },
      ],
      productReady: ["In stock, ready to ship", "#55c53a"],
      productInfo:
        "You'll be reaching for the Got You Hooked Midi Dress every time! This cute dress is designed with a soft and stretchy jersey knit. It features a v-neckline, short sleeves, a functional tie waist, and a relaxed fit with side slits that ends at a midi length. It also has side pockets! Style the Got You Hooked Midi Dress with a denim jacket + sneakers for a casual yet cute outfit! Available in 2 colors.",
      productInfo2: [
        "Soft + Stretchy Knit Fabrication",
        "Rounded Neckline",
        " Short Rolled Sleeves",
        "Relaxed Fit",
        "Front Pocket",
        "Side Pockets",
        "Short/Mini Length",
        "Made in the USA",
        "100% Cotton",
        "Hand Wash Cold, Hang or Line Dry",
        "Model is 5'4' and wearing a Small.",
      ],
    },
  },
  // --------------------------------6 6 6
  {
    id: "my-heart-goes-midi",
    collectionId: "dress",
    images: [
      {
        original: images.dress6_1,
        thumbnail: images.dress6_1,
      },
      {
        original: images.dress6_2,
        thumbnail: images.dress6_2,
      },
      {
        original: images.dress6_3,
        thumbnail: images.dress6_3,
      },
      {
        original: images.dress6_4,
        thumbnail: images.dress6_4,
      },
      {
        original: images.dress6_5,
        thumbnail: images.dress6_5,
      },
      {
        original: images.dress6_6,
        thumbnail: images.dress6_6,
      },
      {
        original: images.dress6_7,
        thumbnail: images.dress6_7,
      },
      {
        original: images.dress6_8,
        thumbnail: images.dress6_8,
      },
      {
        original: images.dress6_9,
        thumbnail: images.dress6_9,
      },
    ],
    suggestionImg: {
      view_1: images.dress1_1,
      view_2: images.dress2_1,
      view_3: images.dress3_1,
      view_4: images.dress7_1,
      view_5: images.dress4_1,
      hoverImg_1: images.dress1_2,
      hoverImg_2: images.dress2_2,
      hoverImg_3: images.dress3_2,
      hoverImg_4: images.dress7_2,
      hoverImg_5: images.dress4_2,
    },
    suggestionInfo: {
      first: "Better Together T-Shirt Dress",
      second: "Easy On The Eyes Midi Dress",
      third: "Fresh Florals Babydoll Mini Dress",
      fourth: "Ocean Waves Halter Maxi Dress",
      fifth: "Steal My Heart Linen Tunic",
    },
    suggestionLink: {
      first: "better-together-t-shirt",
      second: "midi-dress",
      third: "frash-florals-babydoll",
      fourth: "ocean-waves",
      fifth: "steal-my-heart",
    },
    suggestionPrice: {
      first: 15.0,
      second: 15.0,
      third: 20.0,
      fourth: 20.0,
      fifth: 10.0,
    },
    description: {
      productName: "My Heart Goes Midi Dress",
      productPrice: 15.0,
      productColor: [
        {
          color: "#212121",
          sold: false,
          productColorInfo: "black",
        },
        { color: "#e08b4a", sold: false, productColorInfo: "rust" },
        { color: "#ff7f50", sold: false, productColorInfo: "coral" },
        { color: "#a3bad2", sold: false, productColorInfo: "denim" },
        { color: "#c29c6d", sold: false, productColorInfo: "camel" },
        { color: "#c29c6d", sold: true, productColorInfo: "camel" },
      ],
      productSize: [
        { size: "small", sold: false },
        { size: "large", sold: true },
        { size: "medium", sold: true },
        { size: "x-large", sold: true },
      ],
      productReady: ["In stock, ready to ship", "#55c53a"],
      productInfo:
        "A glimpse of you in the My Heart Goes Midi Dress has got our hearts beating fast! This easy going, flowy dress is designed with a lightweight and stretchy woven knit. It features a v-neckline, short sleeves, and a relaxed fit with a split hem and ends at a midi length. Style the My Heart Goes Midi Dress with a platform espadrilles and a straw hat for a beachy summer look! Available in 3 colors.",
      productInfo2: [
        "Soft + Stretchy Knit Fabrication",
        "Rounded Neckline",
        " Short Rolled Sleeves",
        "Relaxed Fit",
        "Front Pocket",
        "Side Pockets",
        "Short/Mini Length",
        "Made in the USA",
        "100% Cotton",
        "Hand Wash Cold, Hang or Line Dry",
        "Model is 5'4' and wearing a Small.",
      ],
    },
  },
  // --------------------------------7 7 7
  {
    id: "ocean-waves",
    collectionId: "dress",
    images: [
      {
        original: images.dress7_1,
        thumbnail: images.dress7_1,
      },
      {
        original: images.dress7_2,
        thumbnail: images.dress7_2,
      },
      {
        original: images.dress7_3,
        thumbnail: images.dress7_3,
      },
      {
        original: images.dress7_4,
        thumbnail: images.dress7_4,
      },
      {
        original: images.dress7_5,
        thumbnail: images.dress7_5,
      },
      {
        original: images.dress7_6,
        thumbnail: images.dress7_6,
      },
      {
        original: images.dress7_7,
        thumbnail: images.dress7_7,
      },
      {
        original: images.dress7_8,
        thumbnail: images.dress7_8,
      },
    ],
    suggestionImg: {
      view_1: images.dress1_1,
      view_2: images.dress2_1,
      view_3: images.dress3_1,
      view_4: images.dress5_1,
      view_5: images.dress4_1,
      hoverImg_1: images.dress1_2,
      hoverImg_2: images.dress2_2,
      hoverImg_3: images.dress3_2,
      hoverImg_4: images.dress5_2,
      hoverImg_5: images.dress4_2,
    },
    suggestionInfo: {
      first: "Better Together T-Shirt Dress",
      second: "Easy On The Eyes Midi Dress",
      third: "Fresh Florals Babydoll Mini Dress",
      fourth: "Got You Hooked Midi Dress",
      fifth: "Steal My Heart Linen Tunic",
    },
    suggestionLink: {
      first: "better-together-t-shirt",
      second: "midi-dress",
      third: "frash-florals-babydoll",
      fourth: "got-you-hooked",
      fifth: "steal-my-heart",
    },
    suggestionPrice: {
      first: 15.0,
      second: 15.0,
      third: 20.0,
      fourth: 10.0,
      fifth: 10.0,
    },
    description: {
      productName: "Ocean Waves Halter Maxi Dress",
      productPrice: 20.0,
      productColor: [
        { color: "#a3bad2", sold: false, productColorInfo: "denim" },
        { color: "#fffff0", sold: false, productColorInfo: "ivory" },
      ],
      productSize: [
        { size: "small", sold: false },
        { size: "large", sold: false },
        { size: "medium", sold: false },
      ],
      productReady: ["In stock, ready to ship", "#55c53a"],
      productInfo:
        "The Ocean Waves Halter Maxi Dress is here to make sure you have an unforgettable getaway! This cute dress is designed with a lightweight woven knit. It features a halter neckline with a functional tie, a smocked tube top lining, a smocked waistband with a functional drawstring tassel tie, and a flowy fit with side slits that ends at a maxi length. Style the Ocean Waves Halter Maxi Dress with sandals for a cute + girly outfit!",
      productInfo2: [
        "Soft + Stretchy Knit Fabrication",
        "Rounded Neckline",
        " Short Rolled Sleeves",
        "Relaxed Fit",
        "Front Pocket",
        "Side Pockets",
        "Short/Mini Length",
        "Made in the USA",
        "100% Cotton",
        "Hand Wash Cold, Hang or Line Dry",
        "Model is 5'4' and wearing a Small.",
      ],
    },
  },
];
